- name: Install Influxdb 
  hosts: all
  strategy: free
  become: true
  tasks:
    - debug:
        msg: "deb https://repos.influxdata.com/{{ hostvars[inventory_hostname].ansible_distribution }} {{ hostvars[inventory_hostname].ansible_distribution_release }} stable"

    - name: Install pip
      script: get-pip.py

    - name: Install python-apt 
      pip:
        name: 
           - python-apt
           - virtualenv
           - setuptools

    - name: Add the InfluxDB apt signing key
      apt_key:
        url: https://repos.influxdata.com/influxdb.key 
        state: present

    - name: Add the InfluxDB apt repository
      apt_repository:
        repo: "deb https://repos.influxdata.com/{{ hostvars[inventory_hostname].ansible_distribution }} {{ hostvars[inventory_hostname].ansible_distribution_release }} stable"
        state: present
     
    - name: Update repositories cache 
      apt: update_cache=yes

    - name: Install InfluxDB 
      apt:
        name: influxdb 
        state: present
